apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
  - image: changeme
    context: .
    docker: {}
  tagPolicy:
    envTemplate:
      template: '{{.DOCKER_REGISTRY}}/abhiram-ampabathina-gmail-com/samplejxspring:{{.VERSION}}'
  local: {}
deploy:
  kubectl: {}
profiles:
- name: dev
  build:
    artifacts:
    - docker: {}
    tagPolicy:
      envTemplate:
        template: '{{.DOCKER_REGISTRY}}/abhiram-ampabathina-gmail-com/samplejxspring:{{.DIGEST_HEX}}'
    local: {}
  deploy:
    helm:
      releases:
      - name: samplejxspring
        chartPath: charts/samplejxspring
        setValueTemplates:
          image.repository: '{{.DOCKER_REGISTRY}}/abhiram-ampabathina-gmail-com/samplejxspring'
          image.tag: '{{.DIGEST_HEX}}'
